// Generated by CoffeeScript 1.8.0
(function() {
  var CoreFunctions, FileUtils, Freesheet, PageFunctions, TableWorksheet, TimeFunctions;

  Freesheet = require('freesheet');

  CoreFunctions = require('core-functions');

  PageFunctions = require('page-functions');

  TimeFunctions = require('time-functions');

  TableWorksheet = require('table-worksheet');

  FileUtils = require('file-utils');

  $(function() {
    var editor, fileLoaded, fileUtils, getPageText, loadFile, parsePage, sheet, tableEl, worksheet;
    tableEl = $('#sheet');
    sheet = Freesheet.createSheet(tableEl.attr('id') || 'sheet1');
    sheet.onValueChange(function(name, value) {
      return console.log("Change: " + name + " = " + value);
    });
    sheet.addFunctions(CoreFunctions);
    sheet.addFunctions(TimeFunctions);
    sheet.addFunctions(PageFunctions);
    editor = CKEDITOR.replace('editor', {
      extraPlugins: 'divarea'
    });
    worksheet = window.worksheet = new TableWorksheet(tableEl, sheet);
    fileUtils = window.fileUtils = new FileUtils();
    getPageText = function() {
      var content, head, initScript, pageHtml, pagePath, sheetScript;
      pagePath = location.href.replace(/\/[^/]+l$/, '');
      head = "<meta charset=\"UTF-8\">\n<link rel=\"stylesheet\" href=\"" + pagePath + "/../../main/css/freesheet-web.css\"/>\n<link rel=\"stylesheet\" href=\"" + pagePath + "/../../main/css/handsontable.full.css\"/>\n<script src=\"" + pagePath + "/../../main/js/lib/jquery.js\"></script>\n<script src=\"" + pagePath + "/../../main/js/lib/freesheet.js\"></script>\n<script src=\"" + pagePath + "/../../../dist/freesheet-web.js\"></script>\n\n<title>Freesheet Active Page</title>";
      content = "<div class=\"content freesheet-template\">\n      " + (editor.getData()) + "\n</div>";
      sheetScript = "<script type=\"text/freesheet\" id=\"sheet1\">\n   " + (worksheet.asText()) + "\n</script>";
      initScript = "<script>\n    require('freesheet-web').loadScriptsIntoWorksheets();\n    require('reactive-template').convertTemplates();\n</script>";
      pageHtml = "<html>\n    <head>\n      " + head + "\n    </head>\n    <body>\n      " + content + "\n      " + sheetScript + "\n      " + initScript + "\n    </body>\n</html>";
      return pageHtml;
    };
    parsePage = function(text) {
      var bodyEl, pageHtml, worksheetText;
      bodyEl = $('<div id="body-mock">' + text.replace(/^[\s\S]*<body.*?>|<\/body>[\s\S]*$/g, '') + '</div>');
      pageHtml = bodyEl.find('.freesheet-template').html();
      worksheetText = bodyEl.find('script[type="text/freesheet"]').html();
      return {
        pageHtml: pageHtml,
        worksheetText: worksheetText
      };
    };
    $('#save').on('click', function() {
      return fileUtils.save(getPageText(), $('#name').val());
    });
    loadFile = $('#load');
    fileLoaded = function(file, text) {
      var pageHtml, worksheetText, _ref;
      _ref = parsePage(text), pageHtml = _ref.pageHtml, worksheetText = _ref.worksheetText;
      worksheet.loadText(worksheetText);
      editor.setData(pageHtml);
      return $('#name').val(file.name);
    };
    return loadFile.on('change', function() {
      return fileUtils.load(loadFile.get(0).files[0], fileLoaded);
    });
  });

}).call(this);

//# sourceMappingURL=activepage.js.map
