// Generated by CoffeeScript 1.8.0
(function() {
  var CoreFunctions, Freesheet, TimeFunctions;

  Freesheet = require('freesheet');

  CoreFunctions = require('core-functions');

  TimeFunctions = require('time-functions');

  $(function() {
    var editor, fileLoaded, fileUtils, getPageText, loadFile, sheet, tableEl, worksheet;
    tableEl = $('#sheet');
    sheet = Freesheet.createSheet(tableEl.attr('id') || 'sheet1');
    sheet.onValueChange(function(name, value) {
      return console.log("Change: " + name + " = " + value);
    });
    sheet.addFunctions(CoreFunctions);
    sheet.addFunctions(TimeFunctions);
    sheet.addFunctions(PageFunctions);
    editor = CKEDITOR.replace('editor', {
      extraPlugins: 'divarea'
    });
    worksheet = window.worksheet = new TableWorksheet(tableEl, sheet);
    fileUtils = window.fileUtils = new FileUtils();
    getPageText = function() {
      var content, pageHtml, sheetScript;
      sheetScript = "<script type=\"text/freesheet\">\n   " + (worksheet.asText()) + "\n</script>";
      content = "<div class=\"content\">\n  " + (editor.getData()) + "\n</div>";
      pageHtml = "<html>\n    <body>\n      " + content + "\n      " + sheetScript + "\n    </body>\n</html>";
      return pageHtml;
    };
    $('#save').on('click', function() {
      return fileUtils.save(getPageText(), $('#name').val());
    });
    loadFile = $('#load');
    fileLoaded = function(file, text) {
      worksheet.loadText(text);
      return $('#name').val(file.name);
    };
    return loadFile.on('change', function() {
      return fileUtils.load(loadFile.get(0).files[0], fileLoaded);
    });
  });

}).call(this);

//# sourceMappingURL=activepage.js.map
