// Generated by CoffeeScript 1.8.0
(function() {
  describe('Freesheet scripts embedded in pages', function() {
    var insertElement, insertScript, removeTestElements, testElements;
    testElements = [];
    insertScript = function(id, text) {
      return insertElement("<script id='" + id + "' type='text/freesheet'>" + text + "</script>");
    };
    insertElement = function(el) {
      var jqEl;
      jqEl = $(el);
      testElements.push(jqEl);
      return jqEl.appendTo($(document.body));
    };
    removeTestElements = function() {
      var el, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = testElements.length; _i < _len; _i++) {
        el = testElements[_i];
        _results.push(el.remove());
      }
      return _results;
    };
    beforeEach(function() {
      return testElements = [];
    });
    afterEach(function() {
      return removeTestElements();
    });
    return it('are loaded and available when loadScripts called', function() {
      var changes, s, storeChanges;
      insertScript('scriptOne', 'a = 10; b = 20; c = a + b');
      Freesheet.loadScripts();
      s = Freesheet.sheets('scriptOne');
      changes = [];
      storeChanges = function(name, value) {
        var received;
        received = {};
        received[name] = value;
        return changes.push(received);
      };
      s.onChange(storeChanges, 'c');
      return changes.should.eql([
        {
          c: 30
        }
      ]);
    });
  });

}).call(this);

//# sourceMappingURL=embeddedScriptSpec.js.map
