// Generated by CoffeeScript 1.8.0
(function() {
  describe('Freesheet scripts embedded in pages', function() {
    return it.skip('are loaded and available when loadScripts called', function() {
      var changes, s, storeChanges;
      insertScript('scriptOne', 'a = 10; b = 20; c = a + b');
      Freesheet.loadScripts();
      s = Freesheet.sheets('scriptOne');
      changes = [];
      storeChanges = function(value) {
        return changes.push(value);
      };
      s.onChange(storeChanges, 'c');
      return changes.should.eql[{
        c: 30
      }];
    });
  });

}).call(this);

//# sourceMappingURL=embeddedScript.js.map
