// Generated by CoffeeScript 1.8.0
(function() {
  var CoreFunctions, Freesheet, TimeFunctions;

  Freesheet = require('freesheet');

  CoreFunctions = require('core-functions');

  TimeFunctions = require('time-functions');

  $(function() {
    var fileLoaded, fileUtils, loadFile, sheet, tableEl, worksheet;
    tableEl = $('#sheet');
    sheet = Freesheet.createSheet(tableEl.attr('id') || 'sheet1');
    sheet.onValueChange(function(name, value) {
      return console.log("Change: " + name + " = " + value);
    });
    sheet.addFunctions(CoreFunctions);
    sheet.addFunctions(TimeFunctions);
    sheet.addFunctions(PageFunctions);
    worksheet = window.worksheet = new TableWorksheet(tableEl, sheet);
    fileUtils = window.fileUtils = new FileUtils();
    $('#save').on('click', function() {
      return fileUtils.save(worksheet.asText(), $('#name').val());
    });
    loadFile = $('#load');
    fileLoaded = function(file, text) {
      worksheet.loadText(text);
      return $('#name').val(file.name);
    };
    return loadFile.on('change', function() {
      return fileUtils.load(loadFile.get(0).files[0], fileLoaded);
    });
  });

}).call(this);

//# sourceMappingURL=worksheet.js.map
