// Generated by CoffeeScript 1.8.0
(function() {
  var PageFunctions, ReactiveRunner, TableWorksheet, TextParser;

  ReactiveRunner = require('reactive-runner');

  TextParser = require('text-parser');

  PageFunctions = require('page-functions');

  TableWorksheet = (function() {
    function TableWorksheet(el, changeCallback) {
      this.el = el;
      this.runner = new ReactiveRunner();
      this.runner.onChange(changeCallback);
      this.runner.addProvidedStreams(PageFunctions);
      this._parseTable(this.runner);
      this.runner.onChange((function(_this) {
        return function(name, value) {
          return _this._updateTable(name, value);
        };
      })(this));
    }

    TableWorksheet.prototype._parseTable = function(runner) {
      var parseFormula, sheetRows, updateFormula;
      parseFormula = function(name, formula) {
        return new TextParser("" + name + " = " + formula).functionDefinition();
      };
      updateFormula = function(name, formula) {
        if (name && formula) {
          return runner.addUserFunction(parseFormula(name, formula));
        }
      };
      sheetRows = this.el.find('tr');
      return sheetRows.each(function() {
        var cells, formula, formulaEl, name, nameEl, rowEl;
        rowEl = $(this);
        cells = rowEl.find('td');
        nameEl = cells.eq(0).find('input');
        name = nameEl.val().trim();
        formulaEl = cells.eq(1).find('input');
        formula = formulaEl.val().trim();
        updateFormula(name, formula);
        return rowEl.on('change', function() {
          return updateFormula(nameEl.val().trim(), formulaEl.val().trim());
        });
      });
    };

    TableWorksheet.prototype._updateTable = function(name, value) {
      var valueCellForName;
      valueCellForName = this.el.find('td:first-child input').filter(function() {
        return $(this).val() === name;
      }).closest('tr').find('td:nth-child(3)');
      return valueCellForName.text(value);
    };

    return TableWorksheet;

  })();

  window.TableWorksheet = TableWorksheet;

}).call(this);

//# sourceMappingURL=TableWorksheet.js.map
